import type { PopPageKey } from "@/lib/popPageCrudConstants"

/** Módulo de suscripción → pantalla POP (permisos CRUD). */
export const POP_ACCESS_MODULE_TO_PAGE_KEY: Record<string, PopPageKey | null> = {
  sale: "sale",
  mesas: "mesas",
  comandas: "comandas",
  mostrador: "mostrador",
  purchases: "purchases",
  expenses: "expenses",
  stock: "articles",
  clients: "clients",
  suppliers: "suppliers",
  promotions: "promotions",
  recipes: "recipes",
  services: "services",
  active_services: "cobrar-servicios",
  inventory: "inventory",
  operations: "operations",
  invoices: "invoices",
  reports: "reports",
  accounts: "accounts",
  hr: "hr",
  settings: "settings",
  printers: "printers",
  cash_registers: "cash-registers",
  current_accounts: "current-accounts",
  checks: "checks",
  statistics: "statistics",
  alerts: "alerts",
  quotes: "quotes",
  purchase_orders: "purchase_orders",
  manufacturing: "manufacturing",
  chat: "chat",
  audit: "audit",
}
