import type { LucideIcon } from "lucide-react"
import {
  Activity,
  BarChart3,
  Bell,
  BookOpen,
  Calculator,
  ClipboardList,
  Cog,
  CreditCard,
  Factory,
  FileBarChart,
  FileCheck,
  FileText,
  Landmark,
  MessageSquare,
  Monitor,
  Package,
  PieChart,
  Printer,
  Receipt,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Truck,
  UserCog,
  Users,
  UtensilsCrossed,
  Wallet,
} from "lucide-react"

const ROOTS_MODULE_ICON_MAP: Record<string, LucideIcon> = {
  clients: Users,
  current_accounts: CreditCard,
  checks: Wallet,
  summary: BarChart3,
  statistics: PieChart,
  reports: FileCheck,
  operations: Activity,
  expenses: Receipt,
  alerts: Bell,
  accounts: Landmark,
  hr: UserCog,
  settings: Cog,
  sale: ShoppingCart,
  purchases: ShoppingBag,
  promotions: Sparkles,
  stock: Package,
  suppliers: Truck,
  quotes: FileText,
  purchase_orders: FileText,
  inventory: ClipboardList,
  cash_registers: Calculator,
  mesas: UtensilsCrossed,
  mostrador: Monitor,
  recipes: BookOpen,
  manufacturing: Factory,
  invoices: FileBarChart,
  printers: Printer,
  chat: MessageSquare,
}

export function getRootsModuleIcon(key: string): LucideIcon {
  return ROOTS_MODULE_ICON_MAP[key] ?? Package
}
